package de.ofenloch.xml.utils;

import org.w3c.dom.Document;

import de.ofenloch.xml.utils.xmlutils;

/**
 * Hello world!
 *
 */
public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
        try {
            // this string was generated by https://onlinerandomtools.com/generate-random-xml
            String xmlString = "<?xml version='1.0' encoding=\"UTF-8\" ?><root><pan>silver</pan><![CDATA[late at]]><shut>-1337919277.7241616</shut><western>wide</western><!--angry it catch salt stiff doubt guard solve heart--><tall morning='into'>valuable</tall><![CDATA[idea political grandfather tube]]><shelf kind=\"touch\">473304764</shelf><top><valley><level><![CDATA[boat clothes basis]]>most</level><star not='fly'>452214570.6772828</star><life>349057767</life><twenty>-1961912868.1009345</twenty><aside>-2033341020.620946</aside><stream band=\"spin\">1201370141.9136739<![CDATA[guess depend]]></stream><![CDATA[never today]]></valley><signal><pack prevent='farmer'>balance</pack><improve fence=\"blood\">follow</improve><planet>fought</planet><!--broke art change purple eye around--><gun>-1928191073.8097696</gun><![CDATA[sat]]><composed>-1657233846</composed><exciting>real</exciting></signal><shadow reason='willing'>opportunity</shadow><continued>194580119</continued><own>from</own><coal football=\"trap\">chair</coal></top><![CDATA[book curious there bee]]></root>";
            Document xmlDocument = xmlutils.loadXMLDocumentFromString(xmlString);
            xmlutils.writeDocToFile(xmlDocument, "./testoutput/output.xml");
        } catch (Exception e) {
            e.printStackTrace();
        }
    } // public static void main(String[] args)
} // public class App
